[2024-10-29T22:19:49.240+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: count_a_dag.sum_results manual__2024-10-29T22:19:37.484795+00:00 [queued]>
[2024-10-29T22:19:49.260+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: count_a_dag.sum_results manual__2024-10-29T22:19:37.484795+00:00 [queued]>
[2024-10-29T22:19:49.261+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-10-29T22:19:49.294+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): sum_results> on 2024-10-29 22:19:37.484795+00:00
[2024-10-29T22:19:49.299+0000] {standard_task_runner.py:57} INFO - Started process 289 to run task
[2024-10-29T22:19:49.303+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'count_a_dag', 'sum_results', 'manual__2024-10-29T22:19:37.484795+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/count_a_dag.py', '--cfg-path', '/tmp/tmpqhetpr4_']
[2024-10-29T22:19:49.305+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask sum_results
[2024-10-29T22:19:49.457+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-29T22:19:49.706+0000] {task_command.py:410} INFO - Running <TaskInstance: count_a_dag.sum_results manual__2024-10-29T22:19:37.484795+00:00 [running]> on host cf88f9d874cd
[2024-10-29T22:19:50.593+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='user' AIRFLOW_CTX_DAG_ID='count_a_dag' AIRFLOW_CTX_TASK_ID='sum_results' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T22:19:37.484795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-29T22:19:37.484795+00:00'
[2024-10-29T22:19:51.228+0000] {logging_mixin.py:150} INFO - Total count of 'a': 3810
[2024-10-29T22:19:51.228+0000] {python.py:183} INFO - Done. Returned value was: None
[2024-10-29T22:19:51.333+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=count_a_dag, task_id=sum_results, execution_date=20241029T221937, start_date=20241029T221949, end_date=20241029T221951
[2024-10-29T22:19:51.406+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-10-29T22:19:51.557+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
